<a href="https://colab.research.google.com/github/GuilhermeSa02/ML_Logic/blob/main/ML_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv('sample_data/train.csv', sep=';')
df

,encounter_id,country,patient_id,race,gender,age,weight,payer_code,outpatient_visits_in_previous_year,emergency_visits_in_previous_year,...,secondary_diagnosis,additional_diagnosis,number_diagnoses,glucose_test_result,a1c_test_result,change_in_meds_during_hospitalization,prescribed_diabetes_meds,medication,readmitted_binary,readmitted_multiclass
0,533192,USA,70110,Caucasian,Female,[70-80),?,?,0,0,...,276,466,8,NaN,NaN,No,No,[],No,>30 days
1,426845,USA,29775006,AfricanAmerican,Male,[50-60),?,?,0,0,...,785,162,9,NaN,NaN,No,Yes,['insulin'],No,No
2,110358,USA,80729253,Caucasian,Female,[60-70),?,?,0,0,...,135,250,6,NaN,NaN,Ch,Yes,"['glimepiride', 'insulin']",No,No
3,628963,USA,2919042,AfricanAmerican,Male,[60-70),?,MC,0,0,...,562,455,5,NaN,NaN,No,No,[],No,No
4,130580,USA,84871971,Caucasian,Female,[70-80),?,HM,1,0,...,599,428,9,NaN,NaN,No,No,[],No,>30 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71231,136517,USA,24531381,AfricanAmerican,Female,[80-90),?,MC,0,1,...,786,250,9,NaN,>7,Ch,Yes,"['metformin', 'glyburide', 'insulin']",No,No
71232,825966,USA,4663818,AfricanAmerican,Female,[70-80),?,?,0,0,...,197,V66,6,NaN,>7,Ch,Yes,"['metformin', 'glyburide']",No,No
71233,332023,USA,23397147,Caucasian,Female,[60-70),?,?,0,2,...,491,276,9,>300,NaN,Ch,Yes,"['glyburide', 'insulin']",Yes,<30 days
71234,495516,USA,52161750,Caucasian,Male,[60-70),?,BC,0,0,...,157,250.8,5,NaN,NaN,Ch,Yes,"['glyburide', 'insulin']",No,No
71235,721770,USA,88410897,Caucasian,Male,[70-80),?,BC,0,0,...,250,401,8,NaN,NaN,Ch,Yes,['insulin'],No,>30 days

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71236 entries, 0 to 71235
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   encounter_id                           71236 non-null  int64
 1   country                                71236 non-null  object
 2   patient_id                             71236 non-null  int64
 3   race                                   67682 non-null  object
 4   gender                                 71236 non-null  object
 5   age                                    67679 non-null  object
 6   weight                                 71236 non-null  object
 7   payer_code                             71236 non-null  object
 8   outpatient_visits_in_previous_year     71236 non-null  int64
 9   emergency_visits_in_previous_year      71236 non-null  int64
 10  inpatient_visits_in_previous_year      71236 non-null  int64
 11  admission_type                         67530 non-null  object
 12  medical_specialty                      71236 non-null  object
 13  average_pulse_bpm                      71236 non-null  int64
 14  discharge_disposition                  68646 non-null  object
 15  admission_source                       66518 non-null  object
 16  length_of_stay_in_hospital             71236 non-null  int64
 17  number_lab_tests                       71236 non-null  int64
 18  non_lab_procedures                     71236 non-null  int64
 19  number_of_medications                  71236 non-null  int64
 20  primary_diagnosis                      71236 non-null  object
 21  secondary_diagnosis                    71236 non-null  object
 22  additional_diagnosis                   71236 non-null  object
 23  number_diagnoses                       71236 non-null  int64
 24  glucose_test_result                    3688 non-null   object
 25  a1c_test_result                        11916 non-null  object
 26  change_in_meds_during_hospitalization  71236 non-null  object
 27  prescribed_diabetes_meds               71236 non-null  object
 28  medication                             71236 non-null  object
 29  readmitted_binary                      71236 non-null  object
 30  readmitted_multiclass                  71236 non-null  object
dtypes: int64(11), object(20)
memory usage: 16.8+ MB

In [18]:
df.replace(['?','[]'], np.nan, inplace=True)
df

,encounter_id,country,patient_id,race,gender,age,weight,payer_code,outpatient_visits_in_previous_year,emergency_visits_in_previous_year,...,secondary_diagnosis,additional_diagnosis,number_diagnoses,glucose_test_result,a1c_test_result,change_in_meds_during_hospitalization,prescribed_diabetes_meds,medication,readmitted_binary,readmitted_multiclass
0,533192,USA,70110,Caucasian,Female,[70-80),NaN,NaN,0,0,...,276,466,8,NaN,NaN,No,No,NaN,No,>30 days
1,426845,USA,29775006,AfricanAmerican,Male,[50-60),NaN,NaN,0,0,...,785,162,9,NaN,NaN,No,Yes,['insulin'],No,No
2,110358,USA,80729253,Caucasian,Female,[60-70),NaN,NaN,0,0,...,135,250,6,NaN,NaN,Ch,Yes,"['glimepiride', 'insulin']",No,No
3,628963,USA,2919042,AfricanAmerican,Male,[60-70),NaN,MC,0,0,...,562,455,5,NaN,NaN,No,No,NaN,No,No
4,130580,USA,84871971,Caucasian,Female,[70-80),NaN,HM,1,0,...,599,428,9,NaN,NaN,No,No,NaN,No,>30 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71231,136517,USA,24531381,AfricanAmerican,Female,[80-90),NaN,MC,0,1,...,786,250,9,NaN,>7,Ch,Yes,"['metformin', 'glyburide', 'insulin']",No,No
71232,825966,USA,4663818,AfricanAmerican,Female,[70-80),NaN,NaN,0,0,...,197,V66,6,NaN,>7,Ch,Yes,"['metformin', 'glyburide']",No,No
71233,332023,USA,23397147,Caucasian,Female,[60-70),NaN,NaN,0,2,...,491,276,9,>300,NaN,Ch,Yes,"['glyburide', 'insulin']",Yes,<30 days
71234,495516,USA,52161750,Caucasian,Male,[60-70),NaN,BC,0,0,...,157,250.8,5,NaN,NaN,Ch,Yes,"['glyburide', 'insulin']",No,No
71235,721770,USA,88410897,Caucasian,Male,[70-80),NaN,BC,0,0,...,250,401,8,NaN,NaN,Ch,Yes,['insulin'],No,>30 days

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71236 entries, 0 to 71235
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   encounter_id                           71236 non-null  int64
 1   country                                71236 non-null  object
 2   patient_id                             71236 non-null  int64
 3   race                                   66166 non-null  object
 4   gender                                 71236 non-null  object
 5   age                                    67679 non-null  object
 6   weight                                 2246 non-null   object
 7   payer_code                             43035 non-null  object
 8   outpatient_visits_in_previous_year     71236 non-null  int64
 9   emergency_visits_in_previous_year      71236 non-null  int64
 10  inpatient_visits_in_previous_year      71236 non-null  int64
 11  admission_type                         67530 non-null  object
 12  medical_specialty                      36314 non-null  object
 13  average_pulse_bpm                      71236 non-null  int64
 14  discharge_disposition                  68646 non-null  object
 15  admission_source                       66518 non-null  object
 16  length_of_stay_in_hospital             71236 non-null  int64
 17  number_lab_tests                       71236 non-null  int64
 18  non_lab_procedures                     71236 non-null  int64
 19  number_of_medications                  71236 non-null  int64
 20  primary_diagnosis                      71220 non-null  object
 21  secondary_diagnosis                    70974 non-null  object
 22  additional_diagnosis                   70228 non-null  object
 23  number_diagnoses                       71236 non-null  int64
 24  glucose_test_result                    3688 non-null   object
 25  a1c_test_result                        11916 non-null  object
 26  change_in_meds_during_hospitalization  71236 non-null  object
 27  prescribed_diabetes_meds               71236 non-null  object
 28  medication                             54890 non-null  object
 29  readmitted_binary                      71236 non-null  object
 30  readmitted_multiclass                  71236 non-null  object
dtypes: int64(11), object(20)
memory usage: 16.8+ MB

In [20]:
df.drop(['readmitted_multiclass','country','encounter_id','patient_id','weight','glucose_test_result'], axis=1,inplace=True)
df

,race,gender,age,payer_code,outpatient_visits_in_previous_year,emergency_visits_in_previous_year,inpatient_visits_in_previous_year,admission_type,medical_specialty,average_pulse_bpm,...,number_of_medications,primary_diagnosis,secondary_diagnosis,additional_diagnosis,number_diagnoses,a1c_test_result,change_in_meds_during_hospitalization,prescribed_diabetes_meds,medication,readmitted_binary
0,Caucasian,Female,[70-80),NaN,0,0,2,Emergency,Family/GeneralPractice,86,...,20,515,276,466,8,NaN,No,No,NaN,No
1,AfricanAmerican,Male,[50-60),NaN,0,0,0,Emergency,NaN,82,...,25,38,785,162,9,NaN,No,Yes,['insulin'],No
2,Caucasian,Female,[60-70),NaN,0,0,1,NaN,Family/GeneralPractice,88,...,22,534,135,250,6,NaN,Ch,Yes,"['glimepiride', 'insulin']",No
3,AfricanAmerican,Male,[60-70),MC,0,0,1,Emergency,InternalMedicine,129,...,9,569,562,455,5,NaN,No,No,NaN,No
4,Caucasian,Female,[70-80),HM,1,0,0,Elective,NaN,121,...,15,715,599,428,9,NaN,No,No,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71231,AfricanAmerican,Female,[80-90),MC,0,1,0,Elective,InternalMedicine,108,...,18,453,786,250,9,>7,Ch,Yes,"['metformin', 'glyburide', 'insulin']",No
71232,AfricanAmerican,Female,[70-80),NaN,0,0,0,Urgent,NaN,66,...,9,157,197,V66,6,>7,Ch,Yes,"['metformin', 'glyburide']",No
71233,Caucasian,Female,[60-70),NaN,0,2,2,NaN,NaN,71,...,24,428,491,276,9,NaN,Ch,Yes,"['glyburide', 'insulin']",Yes
71234,Caucasian,Male,[60-70),BC,0,0,2,Emergency,Emergency/Trauma,98,...,13,820,157,250.8,5,NaN,Ch,Yes,"['glyburide', 'insulin']",No
71235,Caucasian,Male,[70-80),BC,0,0,1,Urgent,Surgery-General,108,...,9,434,250,401,8,NaN,Ch,Yes,['insulin'],No

In [28]:
V_Categorical=['race','age','payer_code','admission_type','medical_specialty','discharge_disposition','admission_source','change_in_meds_during_hospitalization','medication']
V_Binary = ['gender','prescribed_diabetes_meds',]
V_Numeric = ['outpatient_visits_in_previous_year','emergency_visits_in_previous_year','inpatient_visits_in_previous_year','average_pulse_bpm','length_of_stay_in_hospital','number_lab_tests','non_lab_procedures','number_of_medications','primary_diagnosis']

In [ ]:
df['race'].value_counts()

Caucasian          50693
AfricanAmerican    12693
Hispanic            1364
Other                995
Asian                421
Name: race, dtype: int64

In [ ]:
df['country'].value_counts()

USA    71236
Name: country, dtype: int64

In [ ]:
df.corr(method='pearson')

C:\Users\Guilherme Sá\AppData\Local\Temp\ipykernel_58904\1928163937.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr(method='pearson')

,encounter_id,patient_id,outpatient_visits_in_previous_year,emergency_visits_in_previous_year,inpatient_visits_in_previous_year,average_pulse_bpm,length_of_stay_in_hospital,number_lab_tests,non_lab_procedures,number_of_medications,number_diagnoses
encounter_id,1.000000,-0.031140,-0.000351,0.002026,0.005671,0.005323,-0.001332,0.006751,-0.001624,-0.004313,-0.014483
patient_id,-0.031140,1.000000,0.101239,0.063721,0.012676,0.000900,-0.024378,0.015690,-0.018033,0.022089,0.224659
outpatient_visits_in_previous_year,-0.000351,0.101239,1.000000,0.089280,0.103610,-0.001793,-0.007030,-0.006146,-0.021830,0.044112,0.092945
emergency_visits_in_previous_year,0.002026,0.063721,0.089280,1.000000,0.271818,0.002145,-0.009223,0.001985,-0.036403,0.015796,0.057487
inpatient_visits_in_previous_year,0.005671,0.012676,0.103610,0.271818,1.000000,0.008654,0.075453,0.042435,-0.065781,0.066215,0.107992
average_pulse_bpm,0.005323,0.000900,-0.001793,0.002145,0.008654,1.000000,0.005771,0.000237,0.004933,0.002352,0.000803
length_of_stay_in_hospital,-0.001332,-0.024378,-0.007030,-0.009223,0.075453,0.005771,1.000000,0.316575,0.192387,0.464457,0.220691
number_lab_tests,0.006751,0.015690,-0.006146,0.001985,0.042435,0.000237,0.316575,1.000000,0.055058,0.265226,0.154756
non_lab_procedures,-0.001624,-0.018033,-0.021830,-0.036403,-0.065781,0.004933,0.192387,0.055058,1.000000,0.387917,0.074452
number_of_medications,-0.004313,0.022089,0.044112,0.015796,0.066215,0.002352,0.464457,0.265226,0.387917,1.000000,0.261705
number_diagnoses,-0.014483,0.224659,0.092945,0.057487,0.107992,0.000803,0.220691,0.154756,0.074452,0.261705,1.000000

In [ ]:
df['readmitted_binary'].value_counts()

No     63286
Yes     7950
Name: readmitted_binary, dtype: int64

In [ ]:
df['gender'] = df['gender'].map({'Male': 1, 'Female': 0})

In [ ]:
df

,encounter_id,country,patient_id,race,gender,age,weight,payer_code,outpatient_visits_in_previous_year,emergency_visits_in_previous_year,...,secondary_diagnosis,additional_diagnosis,number_diagnoses,glucose_test_result,a1c_test_result,change_in_meds_during_hospitalization,prescribed_diabetes_meds,medication,readmitted_binary,readmitted_multiclass
0,533192,USA,70110,Caucasian,0.0,[70-80),NaN,NaN,0,0,...,276,466,8,NaN,NaN,No,No,[],No,>30 days
1,426845,USA,29775006,AfricanAmerican,1.0,[50-60),NaN,NaN,0,0,...,785,162,9,NaN,NaN,No,Yes,['insulin'],No,No
2,110358,USA,80729253,Caucasian,0.0,[60-70),NaN,NaN,0,0,...,135,250,6,NaN,NaN,Ch,Yes,"['glimepiride', 'insulin']",No,No
3,628963,USA,2919042,AfricanAmerican,1.0,[60-70),NaN,MC,0,0,...,562,455,5,NaN,NaN,No,No,[],No,No
4,130580,USA,84871971,Caucasian,0.0,[70-80),NaN,HM,1,0,...,599,428,9,NaN,NaN,No,No,[],No,>30 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71231,136517,USA,24531381,AfricanAmerican,0.0,[80-90),NaN,MC,0,1,...,786,250,9,NaN,>7,Ch,Yes,"['metformin', 'glyburide', 'insulin']",No,No
71232,825966,USA,4663818,AfricanAmerican,0.0,[70-80),NaN,NaN,0,0,...,197,V66,6,NaN,>7,Ch,Yes,"['metformin', 'glyburide']",No,No
71233,332023,USA,23397147,Caucasian,0.0,[60-70),NaN,NaN,0,2,...,491,276,9,>300,NaN,Ch,Yes,"['glyburide', 'insulin']",Yes,<30 days
71234,495516,USA,52161750,Caucasian,1.0,[60-70),NaN,BC,0,0,...,157,250.8,5,NaN,NaN,Ch,Yes,"['glyburide', 'insulin']",No,No
71235,721770,USA,88410897,Caucasian,1.0,[70-80),NaN,BC,0,0,...,250,401,8,NaN,NaN,Ch,Yes,['insulin'],No,>30 days

In [ ]:
# Find the majority class (0 or 1)
majority_class = df['gender'].mode()[0]

# Replace NaN values with the majority class
df['gender'].fillna(majority_class, inplace=True)

df['gender']=df['gender'].astype(int)

In [ ]:
df['medical_specialty'].value_counts()

InternalMedicine                 10292
Emergency/Trauma                  5319
Family/GeneralPractice            5217
Cardiology                        3716
Surgery-General                   2144
                                 ...
SportsMedicine                       1
Pediatrics-InfectiousDiseases        1
Proctology                           1
Pediatrics-EmergencyMedicine         1
Neurophysiology                      1
Name: medical_specialty, Length: 68, dtype: int64

In [ ]:
# from sklearn.ensemble import RandomForestClassifier

# Define a threshold for grouping categories
threshold = 10

#colocar 100

df['medical_specialty'].fillna("Unknown", inplace=True)

# Count the occurrences of each category
category_counts = df['medical_specialty'].value_counts()

# # Create a classification based on the threshold
df['medical_specialty']=df['medical_specialty'].apply(lambda x: x if category_counts[x] > threshold else 'Others')

In [ ]:
df['medical_specialty'].value_counts()

Unknown                                 34922
InternalMedicine                        10292
Emergency/Trauma                         5319
Family/GeneralPractice                   5217
Cardiology                               3716
Surgery-General                          2144
Nephrology                               1136
Orthopedics                               954
Orthopedics-Reconstructive                867
Radiologist                               817
Pulmonology                               611
Psychiatry                                598
Urology                                   478
ObstetricsandGynecology                   468
Surgery-Cardiovascular/Thoracic           464
Gastroenterology                          397
Surgery-Vascular                          365
Surgery-Neuro                             320
PhysicalMedicineandRehabilitation         280
Oncology                                  243
Pediatrics                                186
Hematology/Oncology                       153
Neurology                                 138
Pediatrics-Endocrinology                  121
Others                                     86
Otolaryngology                             86
Surgery-Thoracic                           83
Endocrinology                              81
Podiatry                                   74
Psychology                                 68
Surgery-Cardiovascular                     67
Pediatrics-CriticalCare                    57
Hematology                                 53
Gynecology                                 50
Radiology                                  39
Hospitalist                                38
Surgeon                                    32
Ophthalmology                              27
Osteopath                                  27
Surgery-Plastic                            25
SurgicalSpecialty                          25
InfectiousDiseases                         23
Obsterics&Gynecology-GynecologicOnco       18
Rheumatology                               16
Obstetrics                                 15
Pediatrics-Pulmonology                     15
Pathology                                  13
Anesthesiology-Pediatric                   12
Name: medical_specialty, dtype: int64

In [ ]:
selected_columns = ['admission_source', 'discharge_disposition', 'medication','medical_specialty', 'readmitted_binary']

# Step 1: Individual Tests for Each Variable
for variable in selected_columns[:-1]:
    contingency_table = pd.crosstab(df[variable], df['readmitted_binary'])
    chi2, p, _, _ = chi2_contingency(contingency_table)
    print(f"Chi-Square Test for Independence: {variable} vs. target")
    print("Chi-Square Statistic:", chi2)
    print("P-value:", p)
    if p < 0.05:
        print(f"{variable} is dependent on 'target'.")
    else:
        print(f"{variable} is independent of 'target'.")
    print()

# Step 2: Gradual Inclusion of Variables
variables_to_test = []
for variable in selected_columns[:-1]:
    variables_to_test.append(variable)
    combined_contingency_table = pd.crosstab([df[var] for var in variables_to_test], df['readmitted_binary'])
    chi2, p, _, _ = chi2_contingency(combined_contingency_table)
    print(f"Combined Chi-Square Test for Independence: {variables_to_test} vs. target")
    print("Chi-Square Statistic:", chi2)
    print("P-value:", p)
    if p < 0.05:
        print(f"At least one of the variables {variables_to_test} is dependent on 'target'.")
    else:
        print(f"All variables {variables_to_test} are independent of 'target'.")
    print()

Chi-Square Test for Independence: admission_source vs. target
Chi-Square Statistic: 35.57143027587476
P-value: 0.002037471495272055
admission_source is dependent on 'target'.

Chi-Square Test for Independence: discharge_disposition vs. target
Chi-Square Statistic: 1127.4037426090542
P-value: 7.183222824260122e-223
discharge_disposition is dependent on 'target'.

Chi-Square Test for Independence: medication vs. target
Chi-Square Statistic: 458.13303800272774
P-value: 1.6119262132237673e-08
medication is dependent on 'target'.

Chi-Square Test for Independence: medical_specialty vs. target
Chi-Square Statistic: 233.66044126764734
P-value: 2.6223653524039013e-20
medical_specialty is dependent on 'target'.

Combined Chi-Square Test for Independence: ['admission_source'] vs. target
Chi-Square Statistic: 35.57143027587476
P-value: 0.002037471495272055
At least one of the variables ['admission_source'] is dependent on 'target'.

Combined Chi-Square Test for Independence: ['admission_source', 'discharge_disposition'] vs. target
Chi-Square Statistic: 1407.1380023557608
P-value: 1.1070438369294316e-214
At least one of the variables ['admission_source', 'discharge_disposition'] is dependent on 'target'.

Combined Chi-Square Test for Independence: ['admission_source', 'discharge_disposition', 'medication'] vs. target
Chi-Square Statistic: 3897.2948349854505
P-value: 8.854895807484643e-80
At least one of the variables ['admission_source', 'discharge_disposition', 'medication'] is dependent on 'target'.

Combined Chi-Square Test for Independence: ['admission_source', 'discharge_disposition', 'medication', 'medical_specialty'] vs. target
Chi-Square Statistic: 7039.856414263637
P-value: 8.175216933181971e-32
At least one of the variables ['admission_source', 'discharge_disposition', 'medication', 'medical_specialty'] is dependent on 'target'.

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

# Assuming you have a DataFrame 'df' with the data
# Define X with all your features and y as the 'target' variable
X = df[['admission_source', 'discharge_disposition', 'medication','medical_specialty']]
y = df[['readmitted_binary']]
# Create a classification model (e.g., Random Forest)
model = RandomForestClassifier()

# Initialize RFE with the model and the number of features to select (you can adjust this number)
rfe = RFE(model, n_features_to_select=3)

# Fit RFE to your data
rfe.fit(X, y)

# Get the selected features
selected_features = X.columns[rfe.support_]

# Print the selected features
print("Selected Features:", selected_features)

ValueError: could not convert string to float: ' Emergency Room'

In [ ]:
df.drop(['readmitted_multiclass','country','encounter_id','patient_id','weight','payer_code'], axis=1,inplace=True)
df

In [ ]:
df['gender'] = df['gender'].map({'Male': 1, 'Female': 0}).fillna(-1).astype(int)
df['gender']

#usar o k means para tentar classificar os NaN

In [ ]:
df['age'].value_counts()

In [ ]:
age_mapping = {
    '[0-10)': 0,
    '[10-20)': 1,
    '[20-30)': 2,
    '[30-40)': 3,
    '[40-50)': 4,
    '[50-60)': 5,
    '[60-70)': 6,
    '[70-80)': 7,
    '[80-90)': 8,
    '[90-100)': 9
}

# Apply the mapping to create a new ordinal column
df['age'] = df['age'].map(age_mapping).fillna(-1).astype(int)

In [ ]:
df['admission_type'].value_counts()

In [ ]:
admission_type_mapping = {
    'Newborn': 0,
    'Not Mapped': 1,
    'Not Available': 2,
    'Elective': 3,
    'Urgent': 4,
    'Emergency': 5,
    'Trauma Center': 6
}

# Apply the mapping to create a new ordinal column
df['admission_type'] = df['admission_type'].map(admission_type_mapping).fillna(-1).astype(int)

In [ ]:
df['medical_specialty'].value_counts()

In [ ]:
y = df.iloc[:, -1]
y

In [ ]:
X = df.drop(df.columns[-1], axis=1)
X

In [ ]:
# from sklearn.feature_selection import RFE
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.preprocessing import LabelEncoder
# # Assuming you have a DataFrame 'df' with your data and the 'target' column for classification

# # Select your categorical variables (features) from the DataFrame
# X_categorical_columns = ['admission_source', 'discharge_disposition', 'medical_specialty', 'medication']

# # Define your target variable
# y

# # Create a classification model (e.g., Random Forest)
# model = RandomForestClassifier()

# # Initialize RFE with the model and the number of features to select (you can adjust this number)
# rfe = RFE(model, n_features_to_select=3)

# # Fit RFE to your data
# rfe.fit(X, y)

# # Get the selected features (categorical variables)
# selected_categorical_features = X.columns[rfe.support_]

# # Print the selected categorical features
# print("Selected Categorical Features:", selected_categorical_features)

In [ ]:
X[col]

In [ ]:
y

In [ ]:
from sklearn.model_selection import train_test_split

# Split your data into a training set and a validation set
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Train a RandomForestClassifier model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Access feature importances
feature_importances = model.feature_importances_

In [ ]:
from sklearn.feature_selection import RFE

# Initialize the model and RFE
model = RandomForestClassifier()
rfe = RFE(model, n_features_to_select=5)  # You can adjust the number of features to select
rfe.fit(X, y)